---
specfile_path: hello.spec
synced_files:
  - hello.spec
upstream_project_name: hello
downstream_package_name: hello
#   post-upstream-clone: "python3 setup.py sdist --dist-dir ."
# current_version_command: ["python3", "setup.py", "--version"]
actions:
  create-archive:
  - python3 setup.py sdist --dist-dir .
  - bash -c 'echo hello-$(python3 setup.py --version).tar.gz'
jobs:
- job: copr_build
  trigger: pull_request
  metadata:
    targets:
    - fedora-29-x86_64
    - fedora-30-x86_64
    - fedora-rawhide-x86_64

- job: tests
  trigger: pull_request
  metadata:
    targets:
    - fedora-29-x86_64
    - fedora-30-x86_64
    - fedora-rawhide-x86_64
